global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: matrix-reciever


receivers:
- name: 'matrix-reciever'
  webhook_configs:
  - url: 'http://matrix-bridge:9094/alerts?secret=INSERT-MATRIX-BRIDGE-SECRET-KEY-HERE'
